### ISSUE TITLE
get a "verified domain" badge for the org account

### ISSUE THREAD

**Issue by maxheld83** [subugoe/subugoe.github.io#2]
as per https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain

(This is an org-wide issue, placing this here in the org website repo out of convention -- has nothing to do with `subugoe.github.io` per se).

CC org owners @hwhw @ipf @jkothe @wm4sub and @njahn82

**Comment by ipf** [comment]
Initiated the verification process

**Comment by ipf** [comment]
The domain is now verified.
