### ISSUE TITLE
remove unused and impersonal accounts

### ISSUE THREAD

**Issue by maxheld83** [subugoe/subugoe.github.io#4]
There seem to be some members in the org, who are inactive and/or appear not to be personal accounts (as per the names), including:

- @wm4sub 
- @univerlag-ed
- @SUBGoe

Perhaps some of these accounts could be encouraged to rename? (I find impersonal accounts that relate to positions, projects or orgs as the above a bit confusing and hard to reason about in terms of security).

Enabling 2FA as per #1 might also purge accounts from the org that aren't in active use.

(This is an org-wide issue, placing this here in the org website repo out of convention -- has nothing to do with `subugoe.github.io` per se).

**Comment by ipf** [comment]
Only one of them (@SUBGoe) is an impersonal Account - created and used by humans solely for work-related purposes
