### ISSUE TITLE
create owners team of users with "owner" privileges

### ISSUE THREAD

**Issue by maxheld83** [subugoe/subugoe.github.io#5]
could you create a team of org owners @hwhw @ipf @jkothe @wm4sub? 
That'd be super cool, because then the rest of us can get in touch more easily by @-mentioning all owners and directly on GitHub if we need something done by owners (such as adding a new org member).

Of course I'd be happy to chip in for owner duties, if I should be so lucky 😸.

(This is an org-wide issue, placing this here in the org website repo out of convention -- has nothing to do with subugoe.github.io per se).

**Comment by ipf** [comment]
Created a team `owners` and invited all the owners.
