### ISSUE TITLE
add new users to org

### ISSUE THREAD

**Issue by maxheld83** [subugoe/subugoe.github.io#6]
could you add the below users (and SUB employees) to the subugoe org @hwhw @ipf @jkothe @wm4sub? 

- [x] @danielbangert [Daniel Bangert](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/daniel-bangert/)
- [x] @Ahobert [Anne Hobert](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/anne-hobert/)
- [x] @jhoeffler [Jan Höffler](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/jan-h-hoeffler/)
- [x] @gitti1 [Birgit Schmidt](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/birgit-schmidt/)

That'd be great, because I want to add them to our WAG teams and such, but can't because I can't add them to the org.

I've tried to batch this as much as possible, but there may be more requests like this.

CC my boss @njahn82.

Crosslisted in https://github.com/subugoe/metaR/issues/21.

(This is an org-wide issue, placing this here in the org website repo out of convention -- has nothing to do with subugoe.github.io per se).

**Comment by ipf** [comment]
All the mentioned people have received an invitation to the org.

**Comment by maxheld83** [comment]
sorry, one more @ipf:

- [x] @Henrieke72 [Henrieke Walter](https://www.sub.uni-goettingen.de/en/contact/staff-a-z/staff-details/person/henrieke-walter/)

**Done, thanks!**
