### ISSUE TITLE
get access to subugoe docker account

### ISSUE THREAD

**Issue by maxheld83** [subugoe/subugoe.github.io#7]
We need to publish to a public docker registry for our [hoad](http://github.com/subugoe/hybrid_oa_dashboard) project.
I noticed that there's already a user (org?) account on https://hub.docker.com/u/subugoe, which has been used in the past by @dneumann @j-panzer and @ipf.

Could one of you also give me access to that account?
(might be useful to [convert the account to an org before](https://docs.docker.com/docker-hub/convert-account/) if it is not already.

My docker account is: https://hub.docker.com/u/maxheld83

**Comment by maxheld83** [comment]
PS:

Long-term, I'd like to migrate entirely to github package registry to cut down on services and auth, but they unfortunately do not offer package downloads without auth as of now, even for public repos.

**Comment by ipf** [comment]
Done!

**Comment by maxheld83** [comment]
thanks!
Could you promote me to owner @ipf ?
Unfortunately I can't create a repo or issue PATs otherwise.
